# Generated by Django 4.1.1 on 2023-05-01 08:16

import KTP_Monitor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KTP_Monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil_info',
            name='div',
            field=models.ForeignKey(default=KTP_Monitor.models.Div_Info.get_default, on_delete=django.db.models.deletion.SET_DEFAULT, to='KTP_Monitor.div_info'),
        ),
        migrations.AlterField(
            model_name='teacher_info',
            name='div',
            field=models.ForeignKey(default=KTP_Monitor.models.Div_Info.get_default, on_delete=django.db.models.deletion.SET_DEFAULT, to='KTP_Monitor.div_info'),
        ),
        migrations.AlterField(
            model_name='teacher_info',
            name='firstname',
            field=models.CharField(default='firstname', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher_info',
            name='lastname',
            field=models.CharField(default='lastname', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher_info',
            name='secondname',
            field=models.CharField(default='secondname', max_length=100),
        ),
    ]
