# Generated by Django 4.1.1 on 2023-04-14 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('KTP_Monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil_Info',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('lastname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('secondname', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('CF', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('e_mail', models.EmailField(max_length=254)),
                ('phone', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Info',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=100)),
                ('CF', models.CharField(max_length=100)),
                ('e_mail', models.EmailField(max_length=254)),
                ('phone_num', models.SlugField()),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RenameField(
            model_name='div_info',
            old_name='div_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='div_info',
            old_name='div_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='div_info',
            old_name='div_year',
            new_name='year',
        ),
        migrations.AddField(
            model_name='teacher_info',
            name='div_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KTP_Monitor.div_info'),
        ),
        migrations.AddField(
            model_name='pupil_info',
            name='div_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KTP_Monitor.div_info'),
        ),
    ]
