# Generated by Django 4.1.7 on 2023-05-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KTP_Monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': (('/main', ''), ('/registration', ''), ('/continue_registration', ''), ('/div_info', ''), ('/divisions', ''), ('/menu', ''), ('/new_division', ''), ('/students', ''), ('/student_profile', ''), ('/signin', ''), ('/registrationRe', ''), ('/profileData', ''), ('/divisionsRe', ''), ('/сhangeDiv', ''), ('/newDivisionRe', ''), ('/profileData/<slug:uidb64>/<slug:token>/', ''), ('/sendProfileData', ''), ('/teacherProfile', ''), ('/editTeacherProfile', ''), ('/contests', ''), ('/contest', ''), ('/currentProfileData', ''), ('/pupilProfile', ''), ('/logout', ''), ('/pupil', ''), ('/students_by_div', ''), ('/teachers_by_div', ''), ('/pupilInfo', ''), ('/pupilStats', ''), ('/division_stats', ''), ('/divisionStats', ''), ('/contestStats', ''), ('/contestsList', ''), ('/deleteDivision', ''), ('/newContest', ''), ('/updateTeacherProfileData', ''), ('/addContest', ''), ('/edit_pupil_profile', ''), ('/deleteContest', ''), ('/updatePupilDivison', ''), ('/studentStatsPage', ''), ('/divs_with_pupil', ''), ('/divs_with_contests', ''), ('/updatePupilProfileData', ''))},
        ),
    ]
