# Generated by Django 4.1.7 on 2023-04-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KTP_Monitor', '0002_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodel',
            options={'permissions': (('/menu', ''), ('/signin', ''), ('/sendProfileData', ''))},
        ),
    ]
