# Generated by Django 4.1.7 on 2023-04-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KTP_Monitor', '0002_remove_teacher_info_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
