# Generated by Django 4.1.7 on 2023-05-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KTP_Monitor', '0002_alter_permissions_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest_info',
            name='last_update',
            field=models.CharField(default='', max_length=100),
        ),
    ]
