# Generated by Django 4.1.7 on 2023-04-16 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KTP_Monitor', '0005_alter_myuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': (('/menu', ''), ('/signin', ''), ('/sendProfileData', ''), ('/teacherProfile', ''), ('/viewProfileData', ''), ('/editTeacherProfile', ''), ('/pupilProfile', ''))},
        ),
    ]
