# Generated by Django 4.1.4 on 2023-04-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KTP_Monitor', '0007_alter_permissions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': (('/menu', ''), ('/signin', ''), ('/sendProfileData', ''), ('/teacherProfile', ''), ('/viewProfileData', ''), ('/editTeacherProfile', ''), ('/pupilProfile', ''), ('/divisions', ''), ('/div_info', ''))},
        ),
    ]
