# Generated by Django 4.1.4 on 2023-04-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KTP_Monitor', '0008_alter_permissions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'permissions': (('/menu', ''), ('/signin', ''), ('/sendProfileData', ''), ('/teacherProfile', ''), ('/viewProfileData', ''), ('/editTeacherProfile', ''), ('/pupilProfile', ''), ('/divisions', ''), ('/div_info', ''), ('/pupil', ''))},
        ),
    ]
